scrape_configs:
  - job_name: 'AuthenticationMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['34.105.33.26:80','host.docker.internal:80']
        labels:
          application: 'authentication'